//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillAssesmentCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        public int teacher_id { get; set; }
        public Nullable<int> disctict_id { get; set; }
        public Nullable<int> institution_id { get; set; }
        public Nullable<int> post_id { get; set; }
        public Nullable<int> subject_id { get; set; }
        public Nullable<int> categories_id { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Institution Institution { get; set; }
        public virtual Posts Posts { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual Discticts Discticts { get; set; }
    }
}
