//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillAssesmentCore
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        public int user_id { get; set; }
        [Required(ErrorMessage = "Логин не может быть пустым")]
        [StringLength(50, ErrorMessage = "Длина строки не может быть больше 50")]
        public string login { get; set; }
        [Required(ErrorMessage = "Пароль не может быть пустым")]
        [StringLength(50, ErrorMessage = "Длина строки не может быть больше 50")]
        public string password { get; set; }
        [Required(ErrorMessage = "Фамилия не может быть пустым")]
        [StringLength(50, ErrorMessage = "Длина строки не может быть больше 50")]
        public string surname { get; set; }
        [Required(ErrorMessage = "Имя не может быть пустым")]
        [StringLength(50, ErrorMessage = "Длина строки не может быть больше 50")]
        public string name { get; set; }
        [Required(ErrorMessage = "Роль не может быть постой")]
        public Nullable<int> role_id { get; set; }
        [Required(ErrorMessage = "Отчество не может быть пустым")]
        [StringLength(50, ErrorMessage = "Длина строки не может быть больше 50")]
        public string patronymic { get; set; }
        public byte[] photo { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
